modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"
logoFile = "logo.png"
logoBlur = false

[[mods]]
modId = "${mod_id}"
version = "${file.jarVersion}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
credits = "This project is made possible with Patreon support from players like you. Thank you! ${mod_supporters}"
authors = "${mod_author}"
description = '''
${mod_description}
'''

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "bookshelf"
mandatory = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"