package net.darkhax.additionalbanners.handler;

import net.darkhax.additionalbanners.handler.PatternHandler.BannerLayer;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.tileentity.BannerPattern;

public class DesignHandler {

    /**
     * An enumeration of all the english alphabet characters and several additional symbols.
     * Credits to pawjwp who created the command used to generate these
     * http://mcstacker.bimbimma.com/#!477
     */
    public static enum LanguageDesign {

        A(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        B(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        C(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        D(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.CURLY_BORDER, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        E(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        F(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        G(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_HORIZONTAL, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_VERTICAL, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        H(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        I(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_CENTER, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        J(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_HORIZONTAL, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        K(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.CROSS, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_VERTICAL, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        L(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        M(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.TRIANGLE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.TRIANGLES_TOP, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        N(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNRIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        O(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        P(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_HORIZONTAL_MIRROR, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        Q(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.RHOMBUS_MIDDLE, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.SQUARE_BOTTOM_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        R(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.HALF_HORIZONTAL, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNRIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        S(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNRIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        T(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_CENTER, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        U(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        V(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNLEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        W(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.TRIANGLE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.TRIANGLES_BOTTOM, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        X(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.CROSS, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        Y(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_DOWNRIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_HORIZONTAL_MIRROR, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_DOWNLEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        Z(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNLEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        PERIOD(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.TRIANGLES_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        EXCLAMATION(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_CENTER, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.TRIANGLES_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        ADD(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRAIGHT_CROSS, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        MINUS(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        MULTIPLY(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.CROSS, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        DIVIDE(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        PERCENT(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.SQUARE_TOP_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.SQUARE_BOTTOM_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNLEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) }),
        MONEY(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNRIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_CENTER, EnumDyeColor.BLACK) }),
        HASHTAG(new PatternHandler.BannerLayer[] { new BannerLayer(PatternHandler.HASHTAG, EnumDyeColor.BLACK) }),
        ONE(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.SQUARE_TOP_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_CENTER, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        TWO(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNLEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        THREE(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        FOUR(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_HORIZONTAL_MIRROR, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        FIVE(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_DOWNRIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        SIX(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_HORIZONTAL, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        SEVEN(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.DIAGONAL_RIGHT, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_DOWNLEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        EIGHT(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        NINE(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.HALF_HORIZONTAL_MIRROR, EnumDyeColor.WHITE), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_MIDDLE, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE), new BannerLayer(PatternHandler.CAP, EnumDyeColor.WHITE) }),
        ZERO(new PatternHandler.BannerLayer[] { new BannerLayer(BannerPattern.STRIPE_RIGHT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_TOP, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_BOTTOM, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.STRIPE_LEFT, EnumDyeColor.BLACK), new BannerLayer(BannerPattern.BORDER, EnumDyeColor.WHITE) });

        /**
         * The layers used by the design.
         */
        private final BannerLayer[] layers;

        LanguageDesign (BannerLayer[] layer) {

            this.layers = layer;
        }

        public BannerLayer[] getLayers () {

            return this.layers;
        }
    }

}
