package net.epoxide.additionalbanners;

import java.util.Arrays;

import net.epoxide.additionalbanners.common.CommonProxy;
import net.epoxide.additionalbanners.handler.BannerPatternHandler;
import net.epoxide.additionalbanners.lib.Constants;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventHandler;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;

@Mod(modid = Constants.MOD_ID, name = Constants.MOD_NAME, version = Constants.VERSION_NUMBER)
public class AdditionalBanners {
    
    @SidedProxy(clientSide = Constants.CLIENT_PROXY_CLASS, serverSide = Constants.SERVER_PROXY_CLASS)
    public static CommonProxy proxy;
    
    @Mod.Instance(Constants.MOD_ID)
    public static AdditionalBanners instance;
    
    @EventHandler
    public void preInit (FMLPreInitializationEvent pre) {
    
        setModInfo(pre.getModMetadata());
        new BannerPatternHandler();
    }
    
    void setModInfo (ModMetadata meta) {
    
        meta.authorList = Arrays.asList("Darkhax");
        meta.logoFile = "/assets/additionalbanners_logo.png";
        meta.credits = "Coded by Darkhax for the Epoxide group.";
        meta.description = "A mod which adds new banner patterns";
        meta.url = "http://darkhax.net";
        meta.autogenerated = false;
    }
}